config/routes.rb
Rails.application.routes.draw do
  resources :confessions do
    member { post :vote}
  end

  devise_for :users
  root  "confessions#index"
  get   "about" => "pages#about"

end

app/models/confession.rb
class Confession < ActiveRecord::Base
	belongs_to :user
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
    validates :description, presence: true

    has_reputation :votes, source: :user,  aggregated_by: :sum

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :confessions       

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confessions_controller.rb
  class ConfessionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_confession, only: [:show, :edit, :update, :destroy]

  # GET /confessions
  # GET /confessions.json
  def index
    @confessions = Confession.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
    @p_confessions = Confession.find_with_reputation(:votes, :all, order: "votes desc")
  end

  # GET /confessions/1
  # GET /confessions/1.json
  def show
    @confession = Confession.find(params[:id])
  end

  def vote
    value = params[:type]  == "up" ? 1 : 0
    @confession = Confession.find(params[:id])
    @confession.add_or_update_evaluation(:votes, value, current_user )
    redirect_to @confession
  end

  # GET /confessions/new
  def new
    @confession = current_user.confessions.build
  end

  # GET /confessions/1/edit
  def edit
  end

  # POST /confessions
  # POST /confessions.json
  def create
    @confession = current_user.confessions.build(confession_params)
    respond_to do |format|
      if @confession.save
        format.html { redirect_to @confession, notice: 'Confession was successfully created.' }
        format.json { render :show, status: :created, location: @confession }
      else
        format.html { render :new }
        format.json { render json: @confession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /confessions/1
  # PATCH/PUT /confessions/1.json
  def update
    respond_to do |format|
      if @confession.update(confession_params)
        format.html { redirect_to @confession, notice: 'Confession was successfully updated.' }
        format.json { render :show, status: :ok, location: @confession }
      else
        format.html { render :edit }
        format.json { render json: @confession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /confessions/1
  # DELETE /confessions/1.json
  def destroy
    @confession.destroy
    respond_to do |format|
      format.html { redirect_to confessions_url, notice: 'Confession was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_confession
      @confession = Confession.find(params[:id])
    end

    def correct_user
      @confession = current_user.confessions.find_by(id: params[:id])
      redirect_to confessions_path, notice: "Not authorized to edit this pin" if @confession.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def confession_params
      params.require(:confession).permit(:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    # Create the user from params
    @user = User.new(params[:user])
    if @user.save
      # Deliver the signup email
      UserNotifier.send_signup_email(@user).deliver
      redirect_to(@user, :notice => 'User created')
    else
      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confessions_helper.rb
module ConfessionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/confessions/_form.html.erb
<%= form_for @confession, html: { multipart: true, class: "col-md-4 col-md-offset-4 center" } do |f| %>
  <% if @confession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@confession.errors.count, "error") %> prohibited this confession from being saved:</h2>

      <ul>
      <% @confession.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
<!--     <%= f.label :description %><br>
 -->    <%= f.text_area :description, class:"form-control", rows: "8" %>
  </div>



  <div class="actions">
    <%= f.submit %>    
  </div>
<% end %>

app/views/confessions/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to UPRM Confessions</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/confessions/edit.html.erb
<h1>Editing confession</h1>

<%= render 'form' %>

<%= link_to 'Show', @confession %> |
<%= link_to 'Back', confessions_path %>

app/views/confessions/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<br>

<div class="col-md-2 col-md-offset-5 center">
  <%= link_to new_confession_path , class: "btn btn-success btn-block cborder" do %>
    <i class="fa fa-pencil"> New confession</i>
  <% end %>
</div>
<br>
<br>
<h1 class="center">Recent Confessions</h1>
<div id="confessions" class="transitions-enabled">
	<!-- This loops states one confession box -->
  <% @confessions.each do |confession| %>
    <%= link_to confession do  %>
        <div class="box panel panel-default">
            <div class="panel-body">"
              <%= confession.description %>
              "
            </div>
            <div class="panel-footer">
                 <i class="fa fa-trophy">
                  <%= pluralize confession.reputation_for(:votes).to_i, "vote" %> 
                </i>
            </div>
        </div>
        
    <% end %>
  <% end %>
</div>




<!-- Bootstrap gem pagination -->
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/confessions/new.html.erb
<h1 class="col-md-12 center">New confession</h1>

<%= render 'form' %>
<br>
<div class="col-md-12">
<%= link_to 'Back', confessions_path, class: "btn btn-info" %>
</div>

app/views/confessions/show.html.erb
<!-- This p is needed for rails alerts -->
<p id="notice"><%= notice %></p>
<%= link_to 'Back', confessions_path, class: "btn btn-info" %>

<div class="row">
	<!-- Div that contains description of the confession -->
	<div class="col-md-offset-3 col-md-6 center">
		<div class="boxx panel panel-default">
			<div class="panel-body">
				<%= @confession.description %> 
			</div>
			<div class="panel-footer">
				<i class="fa fa-trophy">
                  <%= pluralize @confession.reputation_for(:votes).to_i, "vote" %> 
                </i>
                <i class="fa fa-thumbs-up">
				 <%= link_to "Like", vote_confession_path(@confession, type: "up") , method: "post" %>
				</i>
				<i class="fa fa-thumbs-down">
				  <%= link_to "Dislike", vote_confession_path(@confession, type: "down") , method: "post" %>
				</i>
				
			</div>
			
		</div>
		<!-- Div that contains the voting system of the confessions -->

	</div>
</div>
<span class='st_facebook_hcount' displayText='Facebook'></span>



<!-- Link to delete app -->
<% if @confession.user == current_user %>
	<%= link_to  @confession, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } do %>
		<i class="fa fa-trash">Delete</i>
	<% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, class: "navbar-brand" do %>
      <span><i class="fa fa-paw colegial"></i></span> 
      UPRM Confessions
    <% end %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 

      <% if  user_signed_in? %>
        <li> <%= link_to "Settings",  edit_user_registration_path %> </li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %> </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Confessions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "ef620e36-f495-421b-a574-fabd1b8ef1e7", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

</head>
<body>

<%= render 'layouts/header' %>


<div class="container-fluid">
  <!-- needed to display alerts -->
	<% flash.each do |name, msg| %>
	     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
	<%= yield %>
</div>
</body>

</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1><span><i class="fa fa-paw colegial"></i></span> UPRM Confessions </h1>
	<% if user_signed_in? %>
		#do something
	<% else %>
		<p>
			<%= link_to "Log In", new_user_session_path , class: "btn btn-default btn-lg" %> 
			<%= link_to "Sign Up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>

app/views/pages/about.html.erb
<h1>Confessions UPRM</h1>
<p>Confessions UPRM is a website where students can share their deepest secrets</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Confessions</h1>
	<% if user_signed_in? %>
		#do something
	<% else %>
		<p>
			<%= link_to "Log In", new_user_session_path , class: "btn btn-default btn-lg" %>
			<%= link_to "Sign In", new_user_registration_path , class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>

app/views/user_notifier/send_signup_email.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up to Confesiones, <%= @user.email %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and share some awesome secrets</p>
  </body>
</html>